### Задание №1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.linspace(12, 24, num = 12, endpoint = False)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

### Задание №2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape((12, 1))
a2 = a.reshape((6, 2))
a3 = a.reshape((4, 3))
a4 = a.reshape((3, 4))
a5 = a.reshape((2, 6))
a1, a2, a3, a4, a5

(array([[12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.],
        [20.],
        [21.],
        [22.],
        [23.]]),
 array([[12., 13.],
        [14., 15.],
        [16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]),
 array([[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]]),
 array([[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]))

### Задание №3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a1 = a.reshape((12, -1))
a2 = a.reshape((6, -1))
a3 = a.reshape((-1, 3))
a4 = a.reshape((-1, 4))
a5 = a.reshape((-1, 6))
a1, a2, a3, a4, a5

(array([[12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.],
        [20.],
        [21.],
        [22.],
        [23.]]),
 array([[12., 13.],
        [14., 15.],
        [16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]),
 array([[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]]),
 array([[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]))

### Задание №4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет, тк структура, подходящая под это описание - вложенный массив в массив. Конечно, мы можем договориться, что будем считать одномерный массив как конкретнюю строку или столбец, но это будет частность и не отражать реальное положение дел. Ниже я преобразил массив a к виду 1 столбец и 12 строк, а так же 12 столбцов и 1 строка.

In [5]:
a1 = a.reshape((12, 1))
a2 = a.reshape((1, 12))
a1, a1.shape, type(a1), type(a1[0]), a2, a2.shape, type(a2), type(a2[0])


(array([[12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.],
        [20.],
        [21.],
        [22.],
        [23.]]),
 (12, 1),
 numpy.ndarray,
 numpy.ndarray,
 array([[12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]]),
 (1, 12),
 numpy.ndarray,
 numpy.ndarray)

### Задание №5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
np.random.normal(size = (3,4))

array([[ 0.62042688,  0.1913639 ,  1.36729019, -3.33639476],
       [-0.90276959, -0.1022031 , -1.22529568,  0.56603116],
       [ 0.94106943,  1.39284349, -0.2643548 ,  1.17177515]])

### Задание №6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [7]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание №7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [8]:
b = a.reshape((1,-1))
b, b.shape, type(b), type(b[0]), a, a.shape,type(a), type(a[0])

(array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]]),
 (1, 10),
 numpy.ndarray,
 numpy.ndarray,
 array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2]),
 (10,),
 numpy.ndarray,
 numpy.int32)

Делаем вывод, что разница в том, что в случае массива a используется одномерный массив, во втором случае используется двумерный массив

### Задание №8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [9]:
a = np.array([[0, 0],[0, 0]])
b = np.array([[1, 1],[1, 1],[1, 1]])
v = np.vstack((a, b))
a, b, v, a.size, b.size,v.size

(array([[0, 0],
        [0, 0]]),
 array([[1, 1],
        [1, 1],
        [1, 1]]),
 array([[0, 0],
        [0, 0],
        [1, 1],
        [1, 1],
        [1, 1]]),
 4,
 6,
 10)

### Задание №9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [10]:
a = np.arange(0,12)
A = a.reshape((4,3))
At = np.transpose(A)
B = np.matmul(A, At)
B, B.shape, B.size, np.linalg.det(B) == 0

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 (4, 4),
 16,
 True)

Не смотря на то, что размер матрицы B равен 16, определитель матрицы равен нулю, поэтому обратную матрицу вычислить нельзя

### Задание №10

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [11]:
np.random.seed(42)

### Задание №11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [12]:
c = np.random.randint(0,16, size=16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### Задание №12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [13]:
C = c.reshape((4,4))
D = B + (C*10)
Ddet = np.linalg.det(D)
Drang = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
C, D, Ddet, Drang, D_inv

(array([[ 6,  3, 12, 14],
        [10,  7, 12,  4],
        [ 6,  9,  2,  6],
        [10, 10,  7,  4]]),
 array([[ 65,  44, 143, 172],
        [114, 120, 206, 162],
        [ 83, 176, 169, 272],
        [132, 222, 282, 342]]),
 -28511999.999999944,
 4,
 array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
        [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
        [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
        [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]]))

### Задание №13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [15]:
D_inv = np.greater(D_inv, 0).astype('int32')
E = np.where(D_inv, B, C)
D_inv, B, C, E

(array([[1, 1, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [1, 0, 1, 0]]),
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 array([[ 6,  3, 12, 14],
        [10,  7, 12,  4],
        [ 6,  9,  2,  6],
        [10, 10,  7,  4]]),
 array([[  5,  14,  23,  14],
        [ 10,   7,  12, 122],
        [  6,   9,   2, 212],
        [ 32,  10, 212,   4]]))